### ISSUE TITLE
aishell decode error: tensorflow.python.framework.errors_impl.InvalidArgumentError: OpKernel 'ConcatV2'....

### ISSUE THREAD

**Issue by Mitomzhou** [athena-team/athena#100]
when I run aishell decoding scripts independently, Error message below:
_____________________________________________________________
......
None
best_wer_checkpoint:
[]
Traceback (most recent call last):
  File "athena/decode_main.py", line 87, in <module>
    decode(jsonfile, n=5, log_file='nohup.out')
  File "athena/decode_main.py", line 65, in decode
    v = tf.reduce_mean(tf.concat(v,axis=0),axis=0)
  File "/home/bh/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/bh/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 1517, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/bh/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1118, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/home/bh/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: OpKernel 'ConcatV2' has constraint on attr 'T' not in NodeDef '[N=0, Tidx=DT_INT32]', KernelDef: 'op: "ConcatV2" device_type: "GPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "values" host_memory_arg: "axis" host_memory_arg: "output"' [Op:ConcatV2] name: concat
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
......

**Comment by Some-random** [comment]
Please refer to this issue https://github.com/athena-team/athena/issues/80

**Comment by Mitomzhou** [comment]
> Please refer to this issue #80
thanks a lot, I got it.
