### ISSUE TITLE
TIMIT open wav:  wave.Error: file does not start with RIFF id

### ISSUE THREAD

**Issue by Mitomzhou** [athena-team/athena#108]
When I run prepare_data.py  for TIMIT,  function:  get_wave_file_length(wav_file), I got a error below:
 Traceback (most recent call last):
  File " - examples/asr/timit/local/prepare_data.py", line 116, in <module>
    processor(DATASET_DIR, SUBSET, True, OUTPUT_DIR)
  File " - examples/asr/timit/local/prepare_data.py", line 100, in processor
    convert_audio_and_split_transcript(dataset_dir, subset, subset_csv)
  File "- /examples/asr/timit/local/prepare_data.py", line 59, in convert_audio_and_split_transcript
    files_size_dict[wav_file] = get_wave_file_length(wav_file)
  File "- /athena/utils/misc.py", line 103, in get_wave_file_length
    with wave.open(wave_file) as wav_file:
  File "/usr/lib/python3.5/wave.py", line 499, in open
    return Wave_read(f)
  File "/usr/lib/python3.5/wave.py", line 163, in __init__
    self.initfp(f)
  File "/usr/lib/python3.5/wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id

don't surport RIFF?

**Comment by Mitomzhou** [comment]
`I` find a solution for this problem.
1. pip install sphfile
2. transform wav file by bolow code

```
from sphfile import SPHFile
import os

def sphfile_trans_to_wave(wave_file):
    for wav in wave_file:
        file = SPHFile(wav)
        file.write_wav(filename=wav)
 
if __name__ == '__main__':
    data_dir = '~/data/TIMIT' 
    wav_files = []
    for dirpath,dirnames,filenames in os.walk(data_dir):
        for filename in filenames:
                if filename.endswith('.WAV'):
                    wav_files.append(os.path.join(dirpath,filename))
    print(len(wav_files))
    sphfile_trans_to_wave(wav_files)
```
