### ISSUE TITLE
horovod terminated.

### ISSUE THREAD

**Issue by LeoMax-Xiong** [athena-team/athena#110]
``` shell
Pretraining
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:
Wed Apr  8 12:05:13 2020[0]<stderr>:================================= Parse Parameter ==============================
Wed Apr  8 12:05:13 2020[0]<stderr>:
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:hparams: [('batch_size', 64), ('ckpt', 'examples/asr/aishell/ckpts/mpc'), ('cls', 'main'), ('dataset_builder', 'speech_dataset'), ('decode_config', None), ('devset_config', {'data_csv': 'examples/asr/aishell/data/dev.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'input_length_range': [10, 8000]}), ('model', 'mpc'), ('model_config', {'return_encoder_output': False, 'num_filters': 512, 'd_model': 512, 'num_heads': 8, 'num_encoder_layers': 12, 'dff': 1280, 'rate': 0.1, 'chunk_size': 1, 'keep_probability': 0.8}), ('num_classes', 40), ('num_data_threads', 1), ('num_epochs', 250), ('optimizer', 'warmup_adam'), ('optimizer_config', {'d_model': 512, 'warmup_steps': 2000, 'k': 0.3}), ('pretrained_model', None), ('solver_config', {'clip_norm': 100, 'log_interval': 10, 'enable_tf_function': True}), ('solver_gpu', [0]), ('sorta_epoch', 1), ('summary_dir', 'examples/asr/aishell/ckpts/mpc/event'), ('testset_config', {'data_csv': 'examples/asr/aishell/data/test.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'input_length_range': [10, 8000]}), ('trainset_config', {'data_csv': 'examples/asr/aishell/data/train.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'input_length_range': [10, 8000]})]
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:
Wed Apr  8 12:05:13 2020[0]<stderr>:================================= HorovodSolver Init ==============================
Wed Apr  8 12:05:13 2020[0]<stderr>:
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:
Wed Apr  8 12:05:13 2020[0]<stderr>:================================= Start Train ==============================
Wed Apr  8 12:05:13 2020[0]<stderr>:
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:
Wed Apr  8 12:05:13 2020[0]<stderr>:======================= build model from json file ======================
Wed Apr  8 12:05:13 2020[0]<stderr>:
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:hparams: [('batch_size', 64), ('ckpt', 'examples/asr/aishell/ckpts/mpc'), ('cls', 'main'), ('dataset_builder', 'speech_dataset'), ('decode_config', None), ('devset_config', {'data_csv': 'examples/asr/aishell/data/dev.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'input_length_range': [10, 8000]}), ('model', 'mpc'), ('model_config', {'return_encoder_output': False, 'num_filters': 512, 'd_model': 512, 'num_heads': 8, 'num_encoder_layers': 12, 'dff': 1280, 'rate': 0.1, 'chunk_size': 1, 'keep_probability': 0.8}), ('num_classes', 40), ('num_data_threads', 1), ('num_epochs', 250), ('optimizer', 'warmup_adam'), ('optimizer_config', {'d_model': 512, 'warmup_steps': 2000, 'k': 0.3}), ('pretrained_model', None), ('solver_config', {'clip_norm': 100, 'log_interval': 10, 'enable_tf_function': True}), ('solver_gpu', [0]), ('sorta_epoch', 1), ('summary_dir', 'examples/asr/aishell/ckpts/mpc/event'), ('testset_config', {'data_csv': 'examples/asr/aishell/data/test.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'input_length_range': [10, 8000]}), ('trainset_config', {'data_csv': 'examples/asr/aishell/data/train.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'input_length_range': [10, 8000]})]
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:hparams: [('audio_config', {'type': 'Fbank', 'filterbank_channel_count': 40}), ('cls', <class 'athena.data.datasets.speech_set.SpeechDatasetBuilder'>), ('cmvn_file', 'examples/asr/aishell/data/cmvn'), ('data_csv', 'examples/asr/aishell/data/train.csv'), ('input_length_range', [10, 8000])]
Wed Apr  8 12:05:13 2020[0]<stdout>:Fbank params:  [('channel', 1), ('cls', <class 'athena.transform.feats.fbank.Fbank'>), ('delta_delta', False), ('dither', 0.0), ('filterbank_channel_count', 40), ('frame_length', 0.01), ('global_mean', [0.0]), ('global_variance', [1.000001]), ('is_fbank', True), ('local_cmvn', False), ('lower_frequency_limit', 60), ('order', 2), ('output_type', 1), ('preEph_coeff', 0.97), ('raw_energy', 1), ('remove_dc_offset', True), ('snip_edges', 1), ('type', 'Fbank'), ('upper_frequency_limit', 0), ('window', 2), ('window_length', 0.025), ('window_type', 'povey')]
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:Successfully load cmvn file examples/asr/aishell/data/cmvn
Wed Apr  8 12:05:13 2020[0]<stderr>:INFO:absl:Loading data from examples/asr/aishell/data/train.csv
Wed Apr  8 12:05:14 2020[0]<stderr>:2020-04-08 12:05:14.813653: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Wed Apr  8 12:05:14 2020[0]<stderr>:2020-04-08 12:05:14.828699: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399915000 Hz
Wed Apr  8 12:05:14 2020[0]<stderr>:2020-04-08 12:05:14.833653: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55aa3912c090 executing computations on platform Host. Devices:
Wed Apr  8 12:05:14 2020[0]<stderr>:2020-04-08 12:05:14.833693: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Wed Apr  8 12:05:15 2020[0]<stdout>:Model: "x_net"
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:Layer (type)                 Output Shape              Param #
Wed Apr  8 12:05:15 2020[0]<stdout>:=================================================================
Wed Apr  8 12:05:15 2020[0]<stdout>:input_1 (InputLayer)         [(None, None, 40, 1)]     0
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:conv2d (Conv2D)              (None, None, 20, 512)     4608
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:batch_normalization (BatchNo (None, None, 20, 512)     2048
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:tf_op_layer_Relu6 (TensorFlo [(None, None, 20, 512)]   0
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:conv2d_1 (Conv2D)            (None, None, 10, 512)     2359296
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:batch_normalization_1 (Batch (None, None, 10, 512)     2048
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:tf_op_layer_Relu6_1 (TensorF [(None, None, 10, 512)]   0
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:reshape (Reshape)            (None, None, 5120)        0
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:dense (Dense)                (None, None, 512)         2621952
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:positional_encoding (Positio (None, None, 512)         0
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:dropout (Dropout)            (None, None, 512)         0
Wed Apr  8 12:05:15 2020[0]<stdout>:=================================================================
Wed Apr  8 12:05:15 2020[0]<stdout>:Total params: 4,989,952
Wed Apr  8 12:05:15 2020[0]<stdout>:Trainable params: 4,987,904
Wed Apr  8 12:05:15 2020[0]<stdout>:Non-trainable params: 2,048
Wed Apr  8 12:05:15 2020[0]<stdout>:_________________________________________________________________
Wed Apr  8 12:05:15 2020[0]<stdout>:None
Wed Apr  8 12:05:16 2020[0]<stderr>:INFO:absl:trying to restore from : examples/asr/aishell/ckpts/mpc
Wed Apr  8 12:05:20 2020[0]<stderr>:INFO:absl:hparams: [('audio_config', {'type': 'Fbank', 'filterbank_channel_count': 40}), ('cls', <class 'athena.data.datasets.speech_set.SpeechDatasetBuilder'>), ('cmvn_file', 'examples/asr/aishell/data/cmvn'), ('data_csv', 'examples/asr/aishell/data/train.csv'), ('input_length_range', [10, 8000])]
Wed Apr  8 12:05:20 2020[0]<stdout>:Fbank params:  [('channel', 1), ('cls', <class 'athena.transform.feats.fbank.Fbank'>), ('delta_delta', False), ('dither', 0.0), ('filterbank_channel_count', 40), ('frame_length', 0.01), ('global_mean', [0.0]), ('global_variance', [1.000001]), ('is_fbank', True), ('local_cmvn', False), ('lower_frequency_limit', 60), ('order', 2), ('output_type', 1), ('preEph_coeff', 0.97), ('raw_energy', 1), ('remove_dc_offset', True), ('snip_edges', 1), ('type', 'Fbank'), ('upper_frequency_limit', 0), ('window', 2), ('window_length', 0.025), ('window_type', 'povey')]
Wed Apr  8 12:05:21 2020[0]<stderr>:INFO:absl:Successfully load cmvn file examples/asr/aishell/data/cmvn
Wed Apr  8 12:05:21 2020[0]<stderr>:INFO:absl:Loading data from examples/asr/aishell/data/train.csv
Wed Apr  8 12:05:22 2020[0]<stderr>:INFO:absl:Creates the sub-dataset which is the 0 part of 1
Wed Apr  8 12:05:22 2020[0]<stderr>:INFO:absl:
Wed Apr  8 12:05:22 2020[0]<stderr>:>>>>> start training in epoch 0===============================
Wed Apr  8 12:05:22 2020[0]<stderr>:
Wed Apr  8 12:05:22 2020[0]<stderr>:INFO:absl:please be patient, enable tf.function, it takes time ...
Process 0 exit with status code 249.
Traceback (most recent call last):
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/run.py", line 876, in run_commandline
    _run(args)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/run.py", line 844, in _run
    _launch_job(args, remote_host_names, settings, common_intfs, command)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/run.py", line 867, in _launch_job
    gloo_run(settings, remote_host_names, common_intfs, env, driver_ip, command)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 287, in gloo_run
    _launch_jobs(settings, env, host_alloc_plan, remote_host_names, run_command)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 259, in _launch_jobs
    .format(name=name, code=exit_code))
RuntimeError: Gloo job detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 249
```

**Comment by Some-random** [comment]
There isn't enough information in this error log. Can you use single-gpu mode and set **enable_tf_function** to false in config json and post the error message again?

**Comment by LeoMax-Xiong** [comment]
> There isn't enough information in this error log. Can you use single-gpu mode and set **enable_tf_function** to false in config json and post the error message again?

The above is on single-gpu mode and the following log is on `enable_tf_function:false` setting。
``` shell
Wed Apr  8 14:48:57 2020[0]<stderr>:INFO:absl:trying to restore from : examples/asr/aishell/ckpts/mpc
Wed Apr  8 14:49:02 2020[0]<stderr>:INFO:absl:hparams: [('audio_config', {'type': 'Fbank', 'filterbank_channel_count': 40}), ('cls', <class 'athena.data.datasets.speech_set.SpeechDatasetBuilder'>), ('cmvn_file', 'examples/asr/aishell/data/cmvn'), ('data_csv', 'examples/asr/aishell/data/train.csv'), ('input_length_range', [10, 8000])]
Wed Apr  8 14:49:02 2020[0]<stdout>:Fbank params:  [('channel', 1), ('cls', <class 'athena.transform.feats.fbank.Fbank'>), ('delta_delta', False), ('dither', 0.0), ('filterbank_channel_count', 40), ('frame_length', 0.01), ('global_mean', [0.0]), ('global_variance', [1.000001]), ('is_fbank', True), ('local_cmvn', False), ('lower_frequency_limit', 60), ('order', 2), ('output_type', 1), ('preEph_coeff', 0.97), ('raw_energy', 1), ('remove_dc_offset', True), ('snip_edges', 1), ('type', 'Fbank'), ('upper_frequency_limit', 0), ('window', 2), ('window_length', 0.025), ('window_type', 'povey')]
Wed Apr  8 14:49:02 2020[0]<stderr>:INFO:absl:Successfully load cmvn file examples/asr/aishell/data/cmvn
Wed Apr  8 14:49:02 2020[0]<stderr>:INFO:absl:Loading data from examples/asr/aishell/data/train.csv
Wed Apr  8 14:49:04 2020[0]<stderr>:INFO:absl:Creates the sub-dataset which is the 0 part of 1
Wed Apr  8 14:49:04 2020[0]<stderr>:INFO:absl:
Wed Apr  8 14:49:04 2020[0]<stderr>:>>>>> start training in epoch 0 ===============================
Wed Apr  8 14:49:04 2020[0]<stderr>:
Wed Apr  8 14:49:21 2020[0]<stderr>:INFO:absl:
Wed Apr  8 14:49:21 2020[0]<stderr>:========================== Tain Batch: 0 =========================
Process 0 exit with status code 249.
Traceback (most recent call last):
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/run.py", line 876, in run_commandline
    _run(args)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/run.py", line 844, in _run
    _launch_job(args, remote_host_names, settings, common_intfs, command)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/run.py", line 867, in _launch_job
    gloo_run(settings, remote_host_names, common_intfs, env, driver_ip, command)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 287, in gloo_run
    _launch_jobs(settings, env, host_alloc_plan, remote_host_names, run_command)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/horovod/run/gloo_run.py", line 259, in _launch_jobs
    .format(name=name, code=exit_code))
RuntimeError: Gloo job detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 249
```
I locate the code position is that:
```
horovod_main.py:hvd.broadcast_variables(self.model.trainable_variables, root_rank=0) 
```
about line:74

**Comment by Some-random** [comment]
Please execute **python athena/main.py xxx.json** first and check whether it fails or not.

**Comment by LeoMax-Xiong** [comment]
> Please execute **python athena/main.py xxx.json** first and check whether it fails or not.
when I run the above command, it occurs the following error:
``` shell
Traceback (most recent call last):
  File "athena/main.py", line 24, in <module>
    from athena import *
ModuleNotFoundError: No module named 'athena' 
```
And I exec `python setup.py bdist_wheel sdist` and 
`python -m pip install --ignore-installed dist/athena-0.1.0*.whl` 
Now, `python athena/main.py examples/asr/aishell/configs/mpc.json` run successfuly, but run `examples/asr/aishell/run.sh` **with stage 2** , it also cannot run.

**Comment by Some-random** [comment]
If stage 2 fails with the same error message, there must be some issue with Horovod. Please check your Horovod installation first.

**Comment by JianweiSun007** [comment]
Your horovod env maybe install  installation errors. This is a script for auto install horovod in centos and may help you
https://github.com/8z8z8z/athena/blob/master/tools/build_horovod_centos_env.sh
