### ISSUE TITLE
aishell decode error

### ISSUE THREAD

**Issue by LeoMax-Xiong** [athena-team/athena#120]
when I run the aishell example and run the following commdan:
``` shell
python athena/decode_main.py \
          examples/asr/aishell/configs/mtl_transformer_sp.json || exit 1
``` shell
i occurs the following errors:
``` shell
Running decode ...
INFO:absl:hparams: [('batch_size', 32), ('ckpt', 'examples/asr/aishell/ckpts/mtl_transformer_ctc/'), ('cls', 'main'), ('dataset_builder', 'speech_recognition_dataset'), ('decode_config', {'beam_search': True, 'beam_size': 10, 'ctc_weight': 0.5, 'lm_weight': 0.7, 'lm_type': 'rnn', 'lm_path': 'examples/asr/aishell/configs/rnnlm.json'}), ('devset_config', {'data_csv': 'examples/asr/aishell/data/dev.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}, 'input_length_range': [10, 8000]}), ('model', 'mtl_transformer_ctc'), ('model_config', {'model': 'speech_transformer', 'model_config': {'return_encoder_output': True, 'num_filters': 512, 'd_model': 512, 'num_heads': 8, 'num_encoder_layers': 12, 'num_decoder_layers': 6, 'dff': 1280, 'rate': 0.1, 'label_smoothing_rate': 0.0, 'schedual_sampling_rate': 0.9}, 'mtl_weight': 0.5}), ('num_classes', None), ('num_data_threads', 1), ('num_epochs', 2), ('optimizer', 'warmup_adam'), ('optimizer_config', {'d_model': 512, 'warmup_steps': 25000, 'k': 1.0, 'decay_steps': 100000000, 'decay_rate': 0.1}), ('pretrained_model', None), ('solver_config', {'clip_norm': 100, 'log_interval': 10, 'enable_tf_function': True}), ('solver_gpu', [2]), ('sorta_epoch', 1), ('summary_dir', 'examples/asr/aishell/ckpts/mtl_transformer_ctc/event'), ('testset_config', {'data_csv': 'examples/asr/aishell/data/test.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}, 'input_length_range': [10, 8000]}), ('trainset_config', {'data_csv': 'examples/asr/aishell/data/train.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}, 'input_length_range': [10, 8000], 'speed_permutation': [0.9, 1.0, 1.1]})]
2020-04-10 13:37:23.157197: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-10 13:37:23.319318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:02:00.0
2020-04-10 13:37:23.322109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:03:00.0
2020-04-10 13:37:23.324852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:82:00.0
2020-04-10 13:37:23.327557: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:83:00.0
2020-04-10 13:37:23.327807: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-10 13:37:23.329463: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-10 13:37:23.330851: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-10 13:37:23.331178: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-10 13:37:23.333112: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-10 13:37:23.334559: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-10 13:37:23.339604: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-10 13:37:23.358885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3
INFO:absl:hparams: [('batch_size', 32), ('ckpt', 'examples/asr/aishell/ckpts/mtl_transformer_ctc/'), ('cls', 'main'), ('dataset_builder', 'speech_recognition_dataset'), ('decode_config', {'beam_search': True, 'beam_size': 10, 'ctc_weight': 0.5, 'lm_weight': 0.7, 'lm_type': 'rnn', 'lm_path': 'examples/asr/aishell/configs/rnnlm.json'}), ('devset_config', {'data_csv': 'examples/asr/aishell/data/dev.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}, 'input_length_range': [10, 8000]}), ('model', 'mtl_transformer_ctc'), ('model_config', {'model': 'speech_transformer', 'model_config': {'return_encoder_output': True, 'num_filters': 512, 'd_model': 512, 'num_heads': 8, 'num_encoder_layers': 12, 'num_decoder_layers': 6, 'dff': 1280, 'rate': 0.1, 'label_smoothing_rate': 0.0, 'schedual_sampling_rate': 0.9}, 'mtl_weight': 0.5}), ('num_classes', None), ('num_data_threads', 1), ('num_epochs', 2), ('optimizer', 'warmup_adam'), ('optimizer_config', {'d_model': 512, 'warmup_steps': 25000, 'k': 1.0, 'decay_steps': 100000000, 'decay_rate': 0.1}), ('pretrained_model', None), ('solver_config', {'clip_norm': 100, 'log_interval': 10, 'enable_tf_function': True}), ('solver_gpu', [2]), ('sorta_epoch', 1), ('summary_dir', 'examples/asr/aishell/ckpts/mtl_transformer_ctc/event'), ('testset_config', {'data_csv': 'examples/asr/aishell/data/test.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}, 'input_length_range': [10, 8000]}), ('trainset_config', {'data_csv': 'examples/asr/aishell/data/train.csv', 'audio_config': {'type': 'Fbank', 'filterbank_channel_count': 40}, 'cmvn_file': 'examples/asr/aishell/data/cmvn', 'text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}, 'input_length_range': [10, 8000], 'speed_permutation': [0.9, 1.0, 1.1]})]
INFO:absl:hparams: [('audio_config', {'type': 'Fbank', 'filterbank_channel_count': 40}), ('cls', <class 'athena.data.datasets.speech_recognition.SpeechRecognitionDatasetBuilder'>), ('cmvn_file', 'examples/asr/aishell/data/cmvn'), ('data_csv', 'examples/asr/aishell/data/train.csv'), ('input_length_range', [10, 8000]), ('output_length_range', [1, 10000]), ('remove_unk', True), ('speed_permutation', [0.9, 1.0, 1.1]), ('text_config', {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'})]
INFO:absl:Successfully load cmvn file examples/asr/aishell/data/cmvn
INFO:absl:Loading data from examples/asr/aishell/data/train.csv
INFO:absl:perform speed permutation
2020-04-10 13:37:27.546344: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-10 13:37:27.558995: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399915000 Hz
2020-04-10 13:37:27.563122: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56539374f5a0 executing computations on platform Host. Devices:
2020-04-10 13:37:27.563155: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-04-10 13:37:27.724845: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5653937b22c0 executing computations on platform CUDA. Devices:
2020-04-10 13:37:27.724902: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P40, Compute Capability 6.1
2020-04-10 13:37:27.728845: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:82:00.0
2020-04-10 13:37:27.729081: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-10 13:37:27.729156: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-10 13:37:27.729194: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-10 13:37:27.729218: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-10 13:37:27.729238: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-10 13:37:27.729259: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-10 13:37:27.729281: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-10 13:37:27.733483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 2
2020-04-10 13:37:27.733529: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-10 13:37:27.744794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-10 13:37:27.744823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      2 
2020-04-10 13:37:27.744835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2:   N 
2020-04-10 13:37:27.749164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21625 MB memory) -> physical GPU (device: 2, name: Tesla P40, pci bus id: 0000:82:00.0, compute capability: 6.1)
INFO:absl:trying to restore from : examples/asr/aishell/ckpts/mtl_transformer_ctc/
2020-04-10 13:37:34.555450: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-10 13:37:36.219236: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
WARNING:tensorflow:From /home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/ops/ctc_ops.py:1154: alias_inplace_add (from tensorflow.python.ops.inplace_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer tf.tensor_scatter_nd_add, which offers the same functionality with well-defined read-write semantics.
WARNING:tensorflow:From /home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/ops/ctc_ops.py:1154: alias_inplace_add (from tensorflow.python.ops.inplace_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer tf.tensor_scatter_nd_add, which offers the same functionality with well-defined read-write semantics.
WARNING:tensorflow:From /home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/ops/ctc_ops.py:1137: alias_inplace_update (from tensorflow.python.ops.inplace_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer tf.tensor_scatter_nd_update, which offers the same functionality with well-defined read-write semantics.
WARNING:tensorflow:From /home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/ops/ctc_ops.py:1137: alias_inplace_update (from tensorflow.python.ops.inplace_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer tf.tensor_scatter_nd_update, which offers the same functionality with well-defined read-write semantics.
INFO:absl:hparams: [('batch_size', 64), ('ckpt', 'examples/asr/aishell/ckpts/rnnlm'), ('cls', 'main'), ('dataset_builder', 'language_dataset'), ('decode_config', None), ('devset_config', {'data_csv': 'examples/asr/aishell/data/dev.trans.csv', 'input_text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}, 'output_text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}}), ('model', 'rnnlm'), ('model_config', {'d_model': 512, 'rnn_type': 'lstm', 'num_layer': 2, 'dropout_rate': 0.1, 'sos': -1, 'eos': -1}), ('num_classes', None), ('num_data_threads', 1), ('num_epochs', 70), ('optimizer', 'warmup_adam'), ('optimizer_config', {'d_model': 512, 'warmup_steps': 8000, 'k': 0.5, 'decay_steps': 127600, 'decay_rate': 0.1}), ('pretrained_model', None), ('solver_config', {'clip_norm': 100, 'log_interval': 10, 'enable_tf_function': True}), ('solver_gpu', [0]), ('sorta_epoch', 1), ('summary_dir', None), ('testset_config', None), ('trainset_config', {'data_csv': 'examples/asr/aishell/data/train.trans.csv', 'input_text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}, 'output_text_config': {'type': 'vocab', 'model': 'examples/asr/aishell/data/vocab'}})]
INFO:absl:Loading data from examples/asr/aishell/data/train.trans.csv

  0%|          | 0/120097 [00:00<?, ?it/s]
  5%|5         | 6498/120097 [00:00<00:01, 64975.26it/s]
  8%|8         | 9876/120097 [00:00<00:03, 31804.77it/s]
 14%|#4        | 16877/120097 [00:00<00:02, 38030.50it/s]
 20%|#9        | 24012/120097 [00:00<00:02, 44226.36it/s]
 26%|##5       | 31135/120097 [00:00<00:01, 49900.59it/s]
 32%|###1      | 38264/120097 [00:00<00:01, 54836.23it/s]
 38%|###7      | 45363/120097 [00:00<00:01, 58853.80it/s]
 43%|####2     | 51578/120097 [00:01<00:01, 38618.17it/s]
 49%|####8     | 58646/120097 [00:01<00:01, 44700.58it/s]
 55%|#####4    | 65824/120097 [00:01<00:01, 50405.11it/s]
 61%|######    | 73051/120097 [00:01<00:00, 55436.54it/s]
 66%|######6   | 79478/120097 [00:01<00:00, 57644.88it/s]
 72%|#######1  | 85884/120097 [00:01<00:00, 57124.43it/s]
 77%|#######7  | 92985/120097 [00:01<00:00, 60683.90it/s]
 83%|########2 | 99429/120097 [00:02<00:00, 37818.85it/s]
 89%|########8 | 106409/120097 [00:02<00:00, 43844.78it/s]
 94%|#########4| 113381/120097 [00:02<00:00, 49337.77it/s]
100%|##########| 120097/120097 [00:02<00:00, 50981.89it/s]
INFO:absl:trying to restore from : examples/asr/aishell/ckpts/rnnlm
Fbank params:  [('channel', 1), ('cls', <class 'athena.transform.feats.fbank.Fbank'>), ('delta_delta', False), ('dither', 0.0), ('filterbank_channel_count', 40), ('frame_length', 0.01), ('global_mean', [0.0]), ('global_variance', [1.000001]), ('is_fbank', True), ('local_cmvn', False), ('lower_frequency_limit', 60), ('order', 2), ('output_type', 1), ('preEph_coeff', 0.97), ('raw_energy', 1), ('remove_dc_offset', True), ('snip_edges', 1), ('type', 'Fbank'), ('upper_frequency_limit', 0), ('window', 2), ('window_length', 0.025), ('window_type', 'povey')]
Model: "x_net"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, None, 40, 1)]     0         
_________________________________________________________________
conv2d (Conv2D)              (None, None, 20, 512)     4608      
_________________________________________________________________
batch_normalization (BatchNo (None, None, 20, 512)     2048      
_________________________________________________________________
tf_op_layer_Relu6 (TensorFlo [(None, None, 20, 512)]   0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, None, 10, 512)     2359296   
_________________________________________________________________
batch_normalization_1 (Batch (None, None, 10, 512)     2048      
_________________________________________________________________
tf_op_layer_Relu6_1 (TensorF [(None, None, 10, 512)]   0         
_________________________________________________________________
reshape (Reshape)            (None, None, 5120)        0         
_________________________________________________________________
dense (Dense)                (None, None, 512)         2621952   
_________________________________________________________________
positional_encoding (Positio (None, None, 512)         0         
_________________________________________________________________
dropout (Dropout)            (None, None, 512)         0         
=================================================================
Total params: 4,989,952
Trainable params: 4,987,904
Non-trainable params: 2,048
_________________________________________________________________
None
Model: "y_net"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         [(None, None)]            0         
_________________________________________________________________
embedding (Embedding)        (None, None, 512)         2167808   
_________________________________________________________________
positional_encoding_1 (Posit (None, None, 512)         0         
_________________________________________________________________
dropout_1 (Dropout)          (None, None, 512)         0         
=================================================================
Total params: 2,167,808
Trainable params: 2,167,808
Non-trainable params: 0
_________________________________________________________________
None
best_wer_checkpoint: 
[]
Traceback (most recent call last):
  File "athena/decode_main.py", line 87, in <module>
    decode(jsonfile, n=5, log_file='nohup.out')
  File "athena/decode_main.py", line 65, in decode
    v = tf.reduce_mean(tf.concat(v,axis=0),axis=0)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 1431, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/users/xiongxinlei/opt/anaconda2/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1249, in concat_v2
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: OpKernel 'ConcatV2' has constraint on attr 'T' not in NodeDef '[N=0, Tidx=DT_INT32]', KernelDef: 'op: "ConcatV2" device_type: "GPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } } host_memory_arg: "values" host_memory_arg: "axis" host_memory_arg: "output"' [Op:ConcatV2] name: concat
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
```

ALL python package as follows:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
absl-py                   0.9.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
astroid                   2.3.3                    pypi_0    pypi
athena                    0.1.0                    pypi_0    pypi
audioread                 2.1.8                    pypi_0    pypi
binutils_impl_linux-64    2.31.1               h6176602_1
binutils_linux-64         2.31.1               h6176602_9
ca-certificates           2020.1.1                      0
cachetools                4.0.0                    pypi_0    pypi
certifi                   2020.4.5.1               py37_0
cffi                      1.14.0                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               1.3.0                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
flake8                    3.7.9                    pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
gcc_impl_linux-64         7.3.0                habb00fd_1
gcc_linux-64              7.3.0                h553295d_9
google-auth               1.12.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.27.2                   pypi_0    pypi
gxx_impl_linux-64         7.3.0                hdf63c60_1
gxx_linux-64              7.3.0                h553295d_9
h5py                      2.10.0                   pypi_0    pypi
horovod                   0.19.1                   pypi_0    pypi
idna                      2.9                      pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
joblib                    0.14.1                   pypi_0    pypi
kenlm                     0.0.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
lazy-object-proxy         1.4.3                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
librosa                   0.7.2                    pypi_0    pypi
libstdcxx-ng              9.1.0                hdf63c60_0
llvmlite                  0.31.0                   pypi_0    pypi
markdown                  3.2.1                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
ncurses                   6.2                  he6710b0_0
numba                     0.48.0                   pypi_0    pypi
numpy                     1.18.2                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1f               h7b6447c_0
opt-einsum                3.2.0                    pypi_0    pypi
pandas                    1.0.3                    pypi_0    pypi
pip                       20.0.2                   py37_1
protobuf                  3.11.3                   pypi_0    pypi
psutil                    5.7.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.5.0                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pyflakes                  2.1.1                    pypi_0    pypi
pylint                    2.4.4                    pypi_0    pypi
python                    3.7.7           hcf32534_0_cpython
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2019.3                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0
requests                  2.23.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scikit-learn              0.22.2.post1             pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
sentencepiece             0.1.85                   pypi_0    pypi
setuptools                46.1.3                   py37_0
six                       1.14.0                   pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sox                       1.3.7                    pypi_0    pypi
sqlite                    3.31.1               h7b6447c_0
tensorboard               2.0.2                    pypi_0    pypi
tensorflow-estimator      2.0.1                    pypi_0    pypi
tensorflow-gpu            2.0.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0
tqdm                      4.44.1                   pypi_0    pypi
typed-ast                 1.4.1                    pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.4                h14c3975_4
yapf                      0.29.0                   pypi_0    pypi
zlib                      1.2.11               h7b6447c_3
```

**Comment by Some-random** [comment]
Please refer to [this issue](https://github.com/athena-team/athena/issues/80). We will make a pr soon to fix this.
