### ISSUE TITLE
error from nohup.txt

### ISSUE THREAD

**Issue by LuxuryApple** [athena-team/athena#124]
Thanks for your previous suggestion. 
I have change the GPU Server, and install the athena successfully.
I also choose 5% of total data. But there are still some questions. 
The detailed errors are as follows:

INFO:absl:processing S0015
^M  0%|          | 0/1936 [00:00<?, ?it/s]2020-04-12 10:49:57.276320: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at decode_wav_op.cc:55 : Invalid argument: Data too short when trying to read string
2020-04-12 10:49:57.276419: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: Data too short when trying to read string
         [[{{node DecodeWav}}]]
^M 48%|████▊     | 924/1936 [00:00<00:00, 10041.40it/s]
Fbank params:  [('channel', 1), ('cls', <class 'athena.transform.feats.fbank.Fbank'>), ('delta_delta', False), ('dither', 0.0), ('filterbank_channel_count', 40), ('frame_length', 0.01), ('global_mean', [0.0]), ('global_variance', [1.000001]), ('is_fbank', True), ('local_cmvn', False), ('lower_frequency_limit', 60), ('order', 2), ('output_type', 1), ('preEph_coeff', 0.97), ('raw_energy', 1), ('remove_dc_offset', True), ('snip_edges', 1), ('type', 'Fbank'), ('upper_frequency_limit', 0), ('window', 2), ('window_length', 0.025), ('window_type', 'povey')]
Traceback (most recent call last):
  File "athena/cmvn_main.py", line 38, in <module>
    dataset_builder.load_csv(csv_file).compute_cmvn_if_necessary(True)
  File "/home/luxy/athena_demo/athena/athena/data/datasets/speech_set.py", line 206, in compute_cmvn_if_necessary
    self.entries, self.speakers, self.audio_featurizer, feature_dim
  File "/home/luxy/athena_demo/athena/athena/data/feature_normalizer.py", line 67, in compute_cmvn
    feat_data = featurizer(audio_file)
  File "/home/luxy/athena_demo/athena/athena/transform/audio_featurizer.py", line 66, in __call__
    return self.__impl(audio, sr, speed)
  File "/home/luxy/athena_demo/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/luxy/athena_demo/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 494, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/luxy/athena_demo/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/luxy/athena_demo/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/luxy/athena_demo/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/luxy/athena_demo/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/luxy/athena_demo/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Data too short when trying to read string
         [[node DecodeWav (defined at /home/luxy/athena_demo/venv_athena/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference___impl_55]

Function call stack:
__impl

How to solove it?
Thank you very much again.

**Comment by Some-random** [comment]
Root cause of the error is 'Data too short when trying to read string', which means some of the wav files in your training data is too short for our feature extractor to process or there is some non-wave files in your training data.

**Comment by LuxuryApple** [comment]
> Root cause of the error is 'Data too short when trying to read string', which means some of the wav files in your training data is too short for our feature extractor to process or there is some non-wave files in your training data.

But i download the data from "www.openslr.org/resources/33/data_aishell.tgz".  And i did not change the data.  Do i download the data again?

**Comment by Some-random** [comment]
Your data should be ok if it's downloaded from openslr. Can you set batch_size to 1 and print wav names in the process of computing cmvn and check which specific wav file is causing this problem?
