### ISSUE TITLE
Invalid argument: WAV data chunk 'QWDu' is too large

### ISSUE THREAD

**Issue by hanqichen** [athena-team/athena#132]
When I train pretrain stage with thchs30 dataset, an error occured:

> [1,0]<stderr>:INFO:absl:global_steps: 131       learning_rate: 1.9418e-05       loss: 16.4373   AverageLoss: 18.8448    sec/iter: 0.5666
[1,1]<stderr>:2020-04-13 18:04:15.424272: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at decode_wav_op.cc:55 : Invalid argument: WAV data chunk 'QWDu' is too large: 3667229085 bytes, but
 the limit is 2147483647
[1,1]<stderr>:2020-04-13 18:04:15.424419: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: WAV data chunk 'QWDu' is too large: 3667229085
bytes, but the limit is 2147483647
[1,1]<stderr>:   [[{{node DecodeWav}}]]
[1,1]<stderr>:   [[DecodeWav/_2]]
[1,1]<stderr>:2020-04-13 18:04:15.424476: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: WAV data chunk 'QWDu' is too large: 3667229085
bytes, but the limit is 2147483647
[1,1]<stderr>:   [[{{node DecodeWav}}]]
[1,1]<stderr>:2020-04-13 18:04:15.434326: W tensorflow/core/framework/op_kernel.cc:1610] Unknown: InvalidArgumentError: 2 root error(s) found.
[1,1]<stderr>:  (0) Invalid argument:  WAV data chunk 'QWDu' is too large: 3667229085 bytes, but the limit is 2147483647
[1,1]<stderr>:   [[node DecodeWav (defined at /miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
[1,1]<stderr>:   [[DecodeWav/_2]]
[1,1]<stderr>:  (1) Invalid argument:  WAV data chunk 'QWDu' is too large: 3667229085 bytes, but the limit is 2147483647
[1,1]<stderr>:   [[node DecodeWav (defined at /miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
[1,1]<stderr>:0 successful operations.
[1,1]<stderr>:0 derived errors ignored. [Op:__inference___impl_5993]
[1,1]<stderr>:
[1,1]<stderr>:Function call stack:
[1,1]<stderr>:__impl -> __impl
[1,1]<stderr>:
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
[1,1]<stderr>:    ret = func(*args)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 585, in generator_py_func
[1,1]<stderr>:    values = next(generator_state.get_iterator(iterator_id))
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/asr-learning/athena/athena/data/datasets/base.py", line 36, in _gen_data
[1,1]<stderr>:    yield dataset_builder[i]
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/asr-learning/athena/athena/data/datasets/speech_set.py", line 108, in __getitem__
[1,1]<stderr>:    feat = self.audio_featurizer(audio_file)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/asr-learning/athena/athena/transform/audio_featurizer.py", line 66, in __call__
[1,1]<stderr>:    return self.__impl(audio, sr, speed)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
[1,1]<stderr>:    result = self._call(*args, **kwds)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 494, in _call
[1,1]<stderr>:    results = self._stateful_fn(*args, **kwds)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
[1,1]<stderr>:    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
[1,1]<stderr>:    self.captured_inputs)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
[1,1]<stderr>:    ctx, args, cancellation_manager=cancellation_manager)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
[1,1]<stderr>:    ctx=ctx)
[1,1]<stderr>:
[1,1]<stderr>:  File "/home/hanqichen/miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
[1,1]<stderr>:    six.raise_from(core._status_to_exception(e.code, message), None)
[1,1]<stderr>:
[1,1]<stderr>:  File "<string>", line 3, in raise_from
[1,1]<stderr>:
[1,1]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
[1,1]<stderr>:  (0) Invalid argument:  WAV data chunk 'QWDu' is too large: 3667229085 bytes, but the limit is 2147483647
[1,1]<stderr>:   [[node DecodeWav (defined at /miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
[1,1]<stderr>:   [[DecodeWav/_2]]
[1,1]<stderr>:  (1) Invalid argument:  WAV data chunk 'QWDu' is too large: 3667229085 bytes, but the limit is 2147483647
[1,1]<stderr>:   [[node DecodeWav (defined at /miniconda3/envs/athena/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
[1,1]<stderr>:0 successful operations.
[1,1]<stderr>:0 derived errors ignored. [Op:__inference___impl_5993]
[1,1]<stderr>:
[1,1]<stderr>:Function call stack:
[1,1]<stderr>:__impl -> __impl
[1,1]<stderr>:
[1,1]<stderr>:
[1,1]<stderr>:
[1,0]<stderr>:INFO:absl:global_steps: 141       learning_rate: 2.0901e-05       loss: 18.2314   AverageLoss: 17.7826    sec/iter: 0.8311

My mpc.json is 
[mpc.json.txt](https://github.com/athena-team/athena/files/4469078/mpc.json.txt)

What should I do?

**Comment by Some-random** [comment]
@aishinchi please take a look at this. And @hanqichen can you identify which specific wave file is causing this error?

**Comment by Some-random** [comment]
Well, a simple search on Google gave me the following [issue](https://github.com/mozilla/DeepSpeech/issues/2271). Seems like we need special ways to read certain wave files in thchs30 dataset. Can you also take a look at this @aishinchi ?

**Comment by hanqichen** [comment]
I add log print `audio_file`  before 
https://github.com/athena-team/athena/blob/b26e30bde9a1f6216fea93642d7eb09ff905bef6/athena/data/datasets/speech_set.py#L107

The log printing is 
[nohup.out.txt](https://github.com/athena-team/athena/files/4469390/nohup.out.txt)

**Comment by hanqichen** [comment]
Thanks , I will try solution form this [issue](https://github.com/mozilla/DeepSpeech/issues/2271).

**Comment by aishinchi** [comment]
> I add log print `audio_file` before
> 
> https://github.com/athena-team/athena/blob/b26e30bde9a1f6216fea93642d7eb09ff905bef6/athena/data/datasets/speech_set.py#L107
> 
> The log printing is
> [nohup.out.txt](https://github.com/athena-team/athena/files/4469390/nohup.out.txt)

Maybe you can try to use `ffmpeg -i "$name" -c:a copy "tmp/$name"` as [https://github.com/mozilla/DeepSpeech/issues/2271](issue) ?

**Comment by hanqichen** [comment]
> Maybe you can try to use `ffmpeg -i "$name" -c:a copy "tmp/$name"` as [https://github.com/mozilla/DeepSpeech/issues/2271](issue) ?

It's work for this, Thanks
