### ISSUE TITLE
raise error "num samples is empty"

### ISSUE THREAD

**Issue by fming** [athena-team/athena#243]
INFO:absl:>>>>> start evaluate in epoch 0
Traceback (most recent call last):
  File "athena/main.py", line 191, in <module>
    train(json_file, BaseSolver, 1, 0)
  File "athena/main.py", line 169, in train
    devset = devset_builder.as_dataset(p.batch_size, p.num_data_threads)
  File "/home/master/ming/athena/athena/data/datasets/base.py", line 105, in as_dataset
    return data_loader(self, batch_size, num_threads)
  File "/home/master/ming/athena/athena/data/datasets/base.py", line 30, in data_loader
    raise ValueError("num samples is empty")
ValueError: num samples is empty

**Comment by Some-random** [comment]
Please check your **dev.csv** again to make sure file path is correct and files fall into **input_length_range**.
