### ISSUE TITLE
pandas version need to be speficied in requirements.txt

### ISSUE THREAD

**Issue by zhufengyun** [athena-team/athena#289]
pip3 install -r requirements.txt
(pandas-0.25.3 installed)

python3 setup.py bdist_wheel sdist

Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    import tensorflow as tf
  File "/tmp/venv_athena/lib/python3.6/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/tmp/venv_athena/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 45, in <module>
    from . _api.v2 import compat
  File "/tmp/venv_athena/lib/python3.6/site-packages/tensorflow_core/_api/v2/compat/__init__.py", line 23, in <module>
    from . import v1
  File "/tmp/venv_athena/lib/python3.6/site-packages/tensorflow_core/_api/v2/compat/v1/__init__.py", line 664, in <module>
    from tensorflow_estimator.python.estimator.api._v1 import estimator
  File "/tmp/venv_athena/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/tmp/venv_athena/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 12, in <module>
    from tensorflow_estimator._api.v1.estimator import inputs
  File "/tmp/venv_athena/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/inputs/__init__.py", line 11, in <module>
    from tensorflow_estimator.python.estimator.inputs.pandas_io import pandas_input_fn
  File "/tmp/venv_athena/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/inputs/pandas_io.py", line 31, in <module>
    import pandas as pd
  File "/tmp/venv_athena/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/tmp/venv_athena/lib/python3.6/site-packages/pandas/core/api.py", line 24, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/tmp/venv_athena/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (  # noqa: F401
  File "/tmp/venv_athena/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 41, in <module>
    import pandas.core.algorithms as algorithms
AttributeError: module 'pandas' has no attribute 'core'

reinstall pandas-0.22 solved the problem

**Comment by Some-random** [comment]
Thanks for spotting this out. Our pandas version is 0.25.1, I guess we can just add this restriction in requirements.txt.
