### ISSUE TITLE
RuntimeError: Gloo job detected that one or more processes exited with non-zero status

### ISSUE THREAD

**Issue by OswaldoBornemann** [athena-team/athena#94]
When i tried to run the aishell `run.sh` in example directory based on 1 gpu, it shown up the below error. 

```
RuntimeError: Gloo job detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 1
Exit code: 1
```

**Comment by tjadamlee** [comment]
@Some-random please help take look at this issue

**Comment by Some-random** [comment]
> When i tried to run the aishell `run.sh` in example directory based on 1 gpu, it shown up the below error.
> 
> ```
> RuntimeError: Gloo job detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
> Process name: 1
> Exit code: 1
> ```

This seems like an issue with Horovod. Can you comment out $horovod_cmd part in run.sh and run it again?

**Comment by OswaldoBornemann** [comment]
@Some-random Thanks for reply. I have comment out line49 to line54 and also change line27 to `horovod_cmd="horovodrun -np 1 -H localhost:1"`, but still have error.

**Comment by Some-random** [comment]
You don't need to use horovod in single GPU mode. Please change the run command to 'python athena/main.py examples/asr/aishell/configs/xxx.json' and try again.

**Comment by OswaldoBornemann** [comment]
@Some-random I have change line27 to `horovod_cmd="horovodrun -np 2 -H localhost:2"` to use 2 GPUs, and it shown up another error below.

```
[1,0]<stderr>:INFO:absl:trying to restore from : examples/asr/aishell/ckpts/mtl_transformer_ctc/
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "athena/horovod_main.py", line 115, in <module>
[1,0]<stderr>:    train(json_file, HorovodSolver, hvd.size(), hvd.rank())
[1,0]<stderr>:  File "/home/jovyan/data2/peter/athena/athena/main.py", line 117, in train
[1,0]<stderr>:    p, model, optimizer, checkpointer = build_model_from_jsonfile(jsonfile)
[1,0]<stderr>:  File "/home/jovyan/data2/peter/athena/athena/main.py", line 104, in build_model_from_jsonfile
[1,0]<stderr>:    dataset = dataset_builder.as_dataset(p.batch_size)
[1,0]<stderr>:  File "/home/jovyan/data2/peter/athena/athena/data/datasets/base.py", line 105, in as_dataset
[1,0]<stderr>:    return data_loader(self, batch_size, num_threads)
[1,0]<stderr>:  File "/home/jovyan/data2/peter/athena/athena/data/datasets/base.py", line 30, in data_loader
[1,0]<stderr>:    raise ValueError("num samples is empty")
[1,0]<stderr>:ValueError: num samples is empty
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[63593,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by Some-random** [comment]
This error is related to data csv. Is the path of wav files in your train/dev/test csv correct?

**Comment by OswaldoBornemann** [comment]
@Some-random the train/dev/test csv seems empty. 

```
wav_filename  wav_length_ms transcript  speaker
~
~
~
~
~
~
~
~
~
~
```

**Comment by OswaldoBornemann** [comment]
@Some-random It seems that it could not run correctly in data preprocess progress, i will debug it. Thanks a lot 🙏 . 

The data directory is like below.

```
(athena) peter@ubuntu:~/data2/peter/data/test_aishell/data_aishell$ ls
dev  extract_wav.sh  test  train  transcript  wav
```

**Comment by Some-random** [comment]
No problem
